### ISSUE TITLE
eject

### ISSUE THREAD

**Issue by 1mike12** [johnn134/redux_playground#1]
do it, you wont

**Comment by johnn134** [comment]
Thank you valued follower for your contribution to this essential repository. As with all issues raised on codebases integral to the academic progress of associates, every one will be given equal and serious consideration. Unfortunately, this would be the equivalent of playing Russian roulette with nuclear warheads after a 12 year old boy taunted the president.

**Comment by 1mike12** [comment]
I think this was wrongfully closed. Please re-open
